// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkqyyaejdshpbzjiqmib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrcXl5YWVqZHNocGJ6amlxbWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTg1MTMsImV4cCI6MjA3MDYzNDUxM30.xz15lc_t-zoW65n85a90ztB2w89aECpoyYwOIUtzXYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});